[package]
name = "ownership_and_moves"
version = "0.1.0"
authors = ["amarrerod <alemarrerodiaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
